### ISSUE TITLE
Use of JSON over Mojo::JSON (or Mojo::JSON::MaybeXS)

### ISSUE THREAD

**Issue by mrenvoize** [mjemmeson/Mojo-Log-JSON#5]
I'm wondering about the choice of using the pure perl JSON here over Mojo::JSON?

**Comment by mjemmeson** [comment]
Hi,

Mojo::JSON doesn't allow the option of ordering the hash keys, which makes the logs more convenient (human readable, and potentially compressing better, depending on compression algorithm).

"use JSON" will use XS if installed, not just pure Perl. However, these days there are probably better alternatives, like JSON::MaybeXS, which prioritises the CPanel fork over JSON::XS.

Happy to take suggestions on improvements to this if you've got any ideas.

cheers,
Michael

**Comment by mrenvoize** [comment]
Hi Michael,

Thanks for the reply,  I totally missed the canonical flag in there and feel a tad dim now asking the question. 

I'm personally using Mojo::JSON::MaybeXS these days in my mojo based  apps and was hoping to similarly load that in to replace the json parser here with CPanel::JSON::XS.

I'm thinking of adding a gelf sub module much like your logstash one wroth as mojolicious plugin to handle the shipping off of logs to remote server. 

Thanks for your reply 

Martin

**Comment by mjemmeson** [comment]
Hi,

I've just released 0.04 to CPAN - the code has been switched to use JSON::MaybeXS now, which will load JSON::PP, JSON::XS or CPanel::JSON::XS as appropriate. Also it doesn't load anything if you're passing in a 'codec' value, so hopefully shouldn't interfere too much with other code.

thanks,
Michael
